#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d I II III IV V
bspc monitor DP-3 -d VI VII VIII IX X
wmname LG3D

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp-2.10 desktop='^8' state=floating follow=on
bspc rule -a Thunderbird desktop='^1'
bspc rule -a Nextcloud state=floating
bspc rule -a discord desktop='^1'
bspc rule -a Zathura state=tiled
bspc rule -a Pavucontrol state=floating
bspc rule -a Emacs state=tiled

/home/joseph/.config/polybar/launch.sh
nm-applet

notify-send bspwm "WM started"

