#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

name=$(cat /etc/hostname)
if [[ $name == joseph-laptop ]]; then
    bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
else 
    bspc monitor DP-2 -d I II III IV V
    bspc monitor DP-3 -d VI VII VIII IX X
fi

wmname LG3D

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Thunderbird desktop='^1'
bspc rule -a Nextcloud state=floating
bspc rule -a discord desktop='^1'
bspc rule -a Zathura state=tiled
bspc rule -a Pavucontrol state=floating
bspc rule -a Emacs state=tiled
bspc rule -a easy68k.exe state=tiled
bspc rule -a CoreShot state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a st-floating state=floating

/home/joseph/.config/polybar/launch.sh

/home/joseph/bin/test_network.sh &
