#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
pkill -usr1 -x sxhkd

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

#if [[ $(xrandr -q | grep "HDMI1 connected") ]]; then
#    xrandr --output eDP1 --primary --mode 1920x1080 --pos 960x2160 --rotate normal \
#           --output HDMI1 --mode 3840x2160 --pos 0x0 --rotate normal
#    bspc wm -O eDP1 HDMI1
#    bspc monitor eDP1 -d I II III IV V
#    bspc monitor HDMI1 -d VI VII VIII IX X
#else
#fi

wmname LG3D

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Thunderbird desktop='^1'
bspc rule -a Nextcloud state=floating
#bspc rule -a discord desktop='^1'
bspc rule -a Zathura state=tiled
bspc rule -a Pavucontrol state=floating
bspc rule -a Emacs state=tiled
bspc rule -a easy68k.exe state=tiled
bspc rule -a CoreShot state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a st-floating state=floating
bspc rule -a matplotlib state=floating
bspc rule -a lowpower state=floating

/home/joseph/.config/polybar/launch.sh
sleep 1
#bspc config top_padding          0
#polybar-msg cmd hide
